server:
  port: 8083

spring:
  application:
    name: hospital-registration
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital_registration?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hospital.registration.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.hospital.registration.mapper: debug