spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yml
        namespace: hospital-user
        group: DEFAULT_GROUP
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: hospital-user
          uri: lb://hospital-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: hospital-patient
          uri: lb://hospital-patient
          predicates:
            - Path=/api/patient/**
          filters:
            - StripPrefix=1

        - id: hospital-registration
          uri: lb://hospital-registration
          predicates:
            - Path=/api/registration/**
          filters:
            - StripPrefix=1

        - id: hospital-user-auth
          uri: lb://hospital-user
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

# 閰嶇疆鏃ュ織
logging:
  level:
    root: info
    com.hospital: debug
