server:
  port: 8080

spring:
  application:
    name: hospital-gateway
  main:
    web-application-type: reactive
    # 排除数据源自动配置
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  config:
    import: 'optional:nacos:hospital-gateway.yml'
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yml
        namespace: hospital-gateway
        group: DEFAULT_GROUP
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: hospital-user
          uri: lb://hospital-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: hospital-patient
          uri: lb://hospital-patient
          predicates:
            - Path=/api/patient/**
          filters:
            - StripPrefix=1

        - id: hospital-registration
          uri: lb://hospital-registration
          predicates:
            - Path=/api/registration/**
          filters:
            - StripPrefix=1

# 配置日志
logging:
  level:
    root: info
    com.hospital: debug